
import React, { useState, useEffect } from 'react';
import { 
  AreaChart, 
  Area, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer,
  BarChart,
  Bar,
  Cell
} from 'recharts';
import { User } from '../types';
import { 
  ArrowTrendingUpIcon, 
  UserGroupIcon, 
  CursorArrowRaysIcon, 
  BanknotesIcon,
  SparklesIcon,
  LightBulbIcon,
  ArrowRightIcon,
  ChartBarIcon,
  ArrowPathIcon,
  EnvelopeIcon,
  CheckBadgeIcon
} from '@heroicons/react/24/solid';
import { generateSuccessInsight, SuccessInsight } from '../services/geminiService';

const data = [
  { name: 'Mon', clicks: 400, adClicks: 240 },
  { name: 'Tue', clicks: 300, adClicks: 139 },
  { name: 'Wed', clicks: 200, adClicks: 980 },
  { name: 'Thu', clicks: 278, adClicks: 390 },
  { name: 'Fri', clicks: 189, adClicks: 480 },
  { name: 'Sat', clicks: 239, adClicks: 380 },
  { name: 'Sun', clicks: 349, adClicks: 430 },
];

const sourceData = [
  { name: 'TikTok', value: 2400, color: '#6366f1' },
  { name: 'Instagram', value: 1200, color: '#a855f7' },
  { name: 'YouTube', value: 800, color: '#ec4899' },
  { name: 'Podcast', value: 300, color: '#f59e0b' },
];

interface StatsProps {
  user: User;
}

const Stats: React.FC<StatsProps> = ({ user }) => {
  const [insight, setInsight] = useState<SuccessInsight | null>(null);
  const [isLoadingInsight, setIsLoadingInsight] = useState(false);

  // Mock top script data for analysis
  const topScript = "OMG you NEED to see this protein blend, it's a total game changer for my morning routine!";

  useEffect(() => {
    const fetchInsight = async () => {
      setIsLoadingInsight(true);
      try {
        const result = await generateSuccessInsight(topScript, "TikTok", 428);
        setInsight(result);
      } catch (err) {
        console.error(err);
      } finally {
        setIsLoadingInsight(false);
      }
    };
    fetchInsight();
  }, []);

  return (
    <div className="space-y-10 pb-24">
      <header className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Performance Dashboard</h1>
          <p className="text-slate-500 mt-1">Real-time tracking for vendo.page/{user.username}</p>
        </div>
        <div className="flex items-center gap-2 bg-white px-4 py-2 rounded-full border border-slate-200 shadow-sm">
           <div className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></div>
           <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">Syncing with TikTok API</span>
        </div>
      </header>

      {/* Summary Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
        <StatCard 
          icon={<CursorArrowRaysIcon className="w-6 h-6" />}
          label="Total Clicks"
          value="4,289"
          trend="+12% this week"
          color="indigo"
        />
        <StatCard 
          icon={<UserGroupIcon className="w-6 h-6" />}
          label="Uniques"
          value="2,142"
          trend="+5% this week"
          color="purple"
        />
        <StatCard 
          icon={<ArrowTrendingUpIcon className="w-6 h-6" />}
          label="Conv. Rate"
          value="8.4%"
          trend="+1.2% this week"
          color="emerald"
        />
        <StatCard 
          icon={<BanknotesIcon className="w-6 h-6" />}
          label="Est. ROI"
          value="$1.2k"
          trend="Calculated"
          color="amber"
        />
      </div>

      {/* Performance Digest "Email" Style Section */}
      <div className="bg-slate-900 rounded-[3rem] p-8 md:p-12 text-white relative overflow-hidden shadow-2xl shadow-indigo-100 border border-slate-800">
        <div className="absolute top-0 right-0 p-12 opacity-5 pointer-events-none">
          <EnvelopeIcon className="w-64 h-64" />
        </div>
        
        <div className="relative z-10">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 bg-indigo-600 rounded-2xl flex items-center justify-center text-white shadow-xl shadow-indigo-500/20">
                <EnvelopeIcon className="w-8 h-8" />
              </div>
              <div>
                <h2 className="text-2xl font-black tracking-tight">Weekly Success Digest</h2>
                <p className="text-slate-400 font-bold uppercase tracking-widest text-[9px] mt-1">Generated by Vendo Insight Engine</p>
              </div>
            </div>
            
            {isLoadingInsight ? (
              <div className="flex items-center gap-3 px-6 py-3 bg-white/5 rounded-full border border-white/10 animate-pulse">
                <ArrowPathIcon className="w-4 h-4 animate-spin text-indigo-400" />
                <span className="text-[10px] font-black uppercase tracking-widest">Compiling Report...</span>
              </div>
            ) : (
              <div className="px-6 py-3 bg-indigo-500/10 text-indigo-400 rounded-full border border-indigo-500/20 flex items-center gap-3">
                <CheckBadgeIcon className="w-5 h-5" />
                <span className="text-[10px] font-black uppercase tracking-widest">Digest Finalized</span>
              </div>
            )}
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
             <div className="lg:col-span-7 space-y-8">
               <div className="bg-white/5 border border-white/10 rounded-[2.5rem] p-10 md:p-12 shadow-inner">
                 <h3 className="text-[10px] font-black uppercase tracking-[0.3em] text-indigo-400 mb-8">Performance Breakdown</h3>
                 
                 <div className="space-y-6">
                    <p className="text-2xl font-black text-white leading-tight mb-8">
                       {insight?.summaryText || "Your top ad is currently outperforming the market baseline."}
                    </p>
                    
                    {insight ? (
                      <div className="space-y-4">
                         {insight.reasons.map((reason, i) => (
                           <div key={i} className="flex gap-4 items-start group">
                             <span className="text-indigo-500 font-black text-xl mt-[-2px]">→</span>
                             <div className="flex-1">
                               <p className="text-lg font-bold text-slate-200">
                                 <span className="text-white underline decoration-indigo-500/50 underline-offset-4">{reason.value}</span> {reason.description}
                               </p>
                               <span className="text-[9px] font-black text-slate-500 uppercase tracking-widest mt-1 block">{reason.label}</span>
                             </div>
                           </div>
                         ))}
                      </div>
                    ) : (
                      <div className="h-32 flex flex-col justify-center space-y-4">
                         {[1,2,3].map(i => (
                           <div key={i} className="h-4 bg-white/5 rounded-full w-full animate-pulse"></div>
                         ))}
                      </div>
                    )}
                 </div>

                 <div className="mt-12 pt-8 border-t border-white/5">
                    <h4 className="text-[9px] font-black text-slate-500 uppercase tracking-widest mb-4">Top Hook Content</h4>
                    <p className="text-sm font-medium text-slate-400 leading-relaxed italic border-l-2 border-indigo-500/30 pl-4">
                      "{topScript}"
                    </p>
                 </div>
               </div>
             </div>

             <div className="lg:col-span-5 space-y-8">
               <div className="bg-indigo-600 rounded-[2.5rem] p-10 text-white shadow-2xl shadow-indigo-950/40 relative overflow-hidden group">
                  <SparklesIcon className="w-32 h-32 absolute -bottom-10 -right-10 opacity-10 transition-transform group-hover:scale-110 duration-700" />
                  <div className="flex items-center gap-3 mb-6">
                    <LightBulbIcon className="w-6 h-6 text-indigo-200" />
                    <h3 className="text-xl font-black tracking-tight">Replication Strategy</h3>
                  </div>
                  <p className="text-indigo-100 font-bold text-lg leading-relaxed mb-10">
                    {insight?.replicationStrategy || "Loading your custom strategy for next week's campaign..."}
                  </p>
                  <button className="w-full py-5 bg-white text-indigo-600 font-black rounded-2xl hover:bg-indigo-50 transition-all shadow-xl shadow-indigo-950/20 flex items-center justify-center gap-3 active:scale-95">
                    Generate Similar Campaign
                    <ArrowRightIcon className="w-5 h-5" />
                  </button>
               </div>
               
               <div className="p-8 bg-white/5 border border-white/10 rounded-[2rem] flex items-center justify-between">
                  <div>
                    <p className="text-[9px] font-black text-slate-500 uppercase tracking-widest">Next Digest In</p>
                    <p className="text-xl font-black text-white mt-1">6 Days</p>
                  </div>
                  <div className="flex -space-x-3">
                    {[1,2,3].map(i => (
                      <div key={i} className="w-8 h-8 rounded-full border-2 border-slate-900 bg-slate-800 flex items-center justify-center text-[10px] font-black">
                        {i}
                      </div>
                    ))}
                  </div>
               </div>
             </div>
          </div>
        </div>
      </div>

      {/* Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 bg-white p-8 rounded-3xl border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between mb-8">
            <h3 className="text-lg font-bold text-slate-900">Traffic Over Time</h3>
            <div className="flex gap-2">
               <div className="flex items-center gap-1.5 px-3 py-1 bg-indigo-50 text-indigo-600 rounded-lg text-[10px] font-black uppercase tracking-widest">
                  <div className="w-1.5 h-1.5 rounded-full bg-indigo-500"></div>
                  Total Clicks
               </div>
            </div>
          </div>
          <div className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={data}>
                <defs>
                  <linearGradient id="colorClicks" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#6366f1" stopOpacity={0.1}/>
                    <stop offset="95%" stopColor="#6366f1" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#94a3b8', fontSize: 12}} dy={10} />
                <YAxis axisLine={false} tickLine={false} tick={{fill: '#94a3b8', fontSize: 12}} />
                <Tooltip 
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' }}
                />
                <Area type="monotone" dataKey="clicks" stroke="#6366f1" strokeWidth={3} fillOpacity={1} fill="url(#colorClicks)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm">
          <h3 className="text-lg font-bold text-slate-900 mb-8">Traffic Sources</h3>
          <div className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={sourceData} layout="vertical" margin={{ left: -20 }}>
                <XAxis type="number" hide />
                <YAxis dataKey="name" type="category" axisLine={false} tickLine={false} tick={{fill: '#475569', fontWeight: 600, fontSize: 14}} />
                <Tooltip 
                  cursor={{fill: 'transparent'}}
                  contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' }}
                />
                <Bar dataKey="value" radius={[0, 10, 10, 0]} barSize={32}>
                  {sourceData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
};

const StatCard: React.FC<{ icon: React.ReactNode, label: string, value: string, trend: string, color: 'indigo' | 'purple' | 'emerald' | 'amber' }> = ({ icon, label, value, trend, color }) => {
  const colorClasses = {
    indigo: 'bg-indigo-50 text-indigo-600',
    purple: 'bg-purple-50 text-purple-600',
    emerald: 'bg-emerald-50 text-emerald-600',
    amber: 'bg-amber-50 text-amber-600'
  }[color];

  return (
    <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm group hover:border-indigo-500 transition-colors cursor-default">
      <div className={`w-12 h-12 ${colorClasses} rounded-2xl flex items-center justify-center mb-4 transition-transform group-hover:scale-110`}>
        {icon}
      </div>
      <p className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-1">{label}</p>
      <h4 className="text-3xl font-extrabold text-slate-900 mb-1 tracking-tight">{value}</h4>
      <p className={`text-xs font-bold ${color === 'emerald' ? 'text-emerald-600' : 'text-slate-400'}`}>{trend}</p>
    </div>
  );
};

export default Stats;
